/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Honda.gltf 
Author: Alexios Apokaukos (https://sketchfab.com/Alexios_Apokaukos)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/honda-s800-fa6c6113f1e34d9baaff80b5b586a25d
Title: Honda s800
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Honda.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0.595, 0.292, 1.108]}>
        <group rotation={[-Math.PI, 0, -Math.PI]}>
          <mesh geometry={nodes.Object_7.geometry} material={materials.tires_mat} />
          <mesh geometry={nodes.Object_8.geometry} material={materials.EXT_hubcaps} />
          <mesh geometry={nodes.Object_9.geometry} material={materials.rimsblur} />
          <mesh geometry={nodes.Object_10.geometry} material={materials.EXT_RIMS} />
          <mesh geometry={nodes.Object_11.geometry} material={materials.EXT_rim_plastic} />
          <mesh geometry={nodes.Object_12.geometry} material={materials.INT_aluminium} />
          <mesh geometry={nodes.Object_13.geometry} material={materials.INT_black_paint} />
          <mesh geometry={nodes.Object_14.geometry} material={materials.INT_chrome} />
          <mesh geometry={nodes.Object_15.geometry} material={materials.INT_GOLD_mat} />
          <mesh geometry={nodes.Object_16.geometry} material={materials.STW_wood} />
          <mesh geometry={nodes.Object_17.geometry} material={materials.INT_plastic} />
          <mesh geometry={nodes.Object_18.geometry} material={materials.kchain_leather} />
          <mesh geometry={nodes.Object_19.geometry} material={materials.kchain_gloss} />
          <mesh geometry={nodes.Object_20.geometry} material={materials.INT_lights} />
          <mesh geometry={nodes.Object_21.geometry} material={materials.underbody} />
          <mesh geometry={nodes.Object_22.geometry} material={materials.EXT_GRILLE} />
          <mesh geometry={nodes.Object_23.geometry} material={materials.INT_carpet_mat} />
          <mesh geometry={nodes.Object_24.geometry} material={materials.INT_carpet_border} />
          <mesh geometry={nodes.Object_25.geometry} material={materials.INT_LEATHER_mat} />
          <mesh geometry={nodes.Object_26.geometry} material={materials.INT_dashboard} />
          <mesh geometry={nodes.Object_27.geometry} material={materials.INT_dashpanel} />
          <mesh geometry={nodes.Object_28.geometry} material={materials.EXT_rubber} />
          <mesh geometry={nodes.Object_29.geometry} material={materials.mirrors_mat} />
          <mesh geometry={nodes.Object_30.geometry} material={materials.image_gauge_faces} />
          <mesh geometry={nodes.Object_31.geometry} material={materials.kchain_plastic} />
          <mesh geometry={nodes.Object_32.geometry} material={materials.INT_decals_BL} />
          <mesh geometry={nodes.Object_33.geometry} material={materials.INT_SEATBELTS} />
          <mesh geometry={nodes.Object_34.geometry} material={materials.EXT_badges_plate} />
          <mesh geometry={nodes.Object_35.geometry} material={materials.sidesteps} />
          <mesh geometry={nodes.Object_36.geometry} material={materials.FLAT_TOP_FABRIC_MAT} />
          <mesh geometry={nodes.Object_37.geometry} material={materials.hedlights_ON} />
          <mesh geometry={nodes.Object_38.geometry} material={materials.INT_windshield} />
          <mesh geometry={nodes.Object_39.geometry} material={materials.chrome_mat} />
          <mesh geometry={nodes.Object_40.geometry} material={materials.exhausts_stock} />
          <mesh geometry={nodes.Object_41.geometry} material={materials.EXT_headlight_glass} />
          <mesh geometry={nodes.Object_42.geometry} material={materials.EXT_badges} />
          <mesh geometry={nodes.Object_43.geometry} material={materials.EXT_paint} />
          <mesh geometry={nodes.Object_44.geometry} material={materials.plastic_reflective} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Honda.gltf')
