/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Mustang.gltf 
Author: ₦₥₵ ฿₵ (https://sketchfab.com/nmcbc)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/car-4-3d-model-0bb02eb19b594617bf4f71d75893d52b
Title: Car # 4  3D Model
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Mustang.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0.284, -0.846, 0.892]} rotation={[0.767, -1.565, -0.805]} scale={[0.322, 1.03, 1.065]}>
          <mesh geometry={nodes.Object_7.geometry} material={materials['Material0-material']} />
          <mesh geometry={nodes.Object_9.geometry} material={materials['Material1-material']} />
          <mesh geometry={nodes.Object_11.geometry} material={materials['Material2-material']} />
          <mesh geometry={nodes.Object_13.geometry} material={materials['Material3-material']} />
          <mesh geometry={nodes.Object_15.geometry} material={materials['Material4-material']} />
          <mesh geometry={nodes.Object_17.geometry} material={materials['Material5-material']} />
          <mesh geometry={nodes.Object_19.geometry} material={materials['Material6-material']} />
        </group>
        <group position={[-0.644, -0.853, 0.898]} rotation={[0.766, -1.565, -0.805]} scale={[0.336, 1.033, 1.093]}>
          <mesh geometry={nodes.Object_22.geometry} material={materials['Material3-material']} />
          <mesh geometry={nodes.Object_24.geometry} material={materials['Material6-material']} />
          <mesh geometry={nodes.Object_26.geometry} material={materials['Material7-material']} />
          <mesh geometry={nodes.Object_28.geometry} material={materials['Material8-material']} />
          <mesh geometry={nodes.Object_30.geometry} material={materials['Material9-material']} />
          <mesh geometry={nodes.Object_32.geometry} material={materials['Material10-material']} />
        </group>
        <mesh geometry={nodes.Object_35.geometry} material={materials['Material11-material']} position={[2.406, -0.763, 0.593]} rotation={[0.767, -1.565, -0.805]} scale={[0.391, 0.3, 0.092]} />
        <group position={[-0.794, 0.024, 0.727]} rotation={[0.767, -1.565, -0.805]} scale={[1.723, 0.81, 4.153]}>
          <mesh geometry={nodes.Object_38.geometry} material={materials['Material12-material']} />
          <mesh geometry={nodes.Object_40.geometry} material={materials['Material13-material']} />
          <mesh geometry={nodes.Object_42.geometry} material={materials['Material14-material']} />
          <mesh geometry={nodes.Object_44.geometry} material={materials['Material15-material']} />
          <mesh geometry={nodes.Object_46.geometry} material={materials['Material16-material']} />
        </group>
        <mesh geometry={nodes.Object_49.geometry} material={materials['Material17-material']} position={[1.643, -0.685, 0.37]} rotation={[0.766, -1.565, -0.805]} scale={[0.226, 0.337, 0.366]} />
        <group position={[-0.651, 0.902, 0.898]} rotation={[0.766, -1.565, -0.805]} scale={[0.336, 1.033, 1.093]}>
          <mesh geometry={nodes.Object_52.geometry} material={materials['Material3-material']} />
          <mesh geometry={nodes.Object_54.geometry} material={materials['Material6-material']} />
          <mesh geometry={nodes.Object_56.geometry} material={materials['Material18-material']} />
          <mesh geometry={nodes.Object_58.geometry} material={materials['Material19-material']} />
          <mesh geometry={nodes.Object_60.geometry} material={materials['Material20-material']} />
        </group>
        <mesh geometry={nodes.Object_63.geometry} material={materials['Material21-material']} position={[-0.599, 0.025, 0.417]} rotation={[0.767, -1.565, -0.805]} scale={[1.873, 0.414, 3.331]} />
        <group position={[1.729, 0.034, 0.9]} rotation={[0.767, -1.565, -0.805]} scale={[1.534, 0.269, 1.594]}>
          <mesh geometry={nodes.Object_66.geometry} material={materials['Material6-material']} />
          <mesh geometry={nodes.Object_68.geometry} material={materials['Material22-material']} />
        </group>
        <mesh geometry={nodes.Object_71.geometry} material={materials['Material23-material']} position={[0.84, 0.394, 0.911]} rotation={[0.766, -1.565, -0.805]} scale={[0.745, 0.15, 0.162]} />
        <mesh geometry={nodes.Object_74.geometry} material={materials['Material24-material']} position={[-0.889, 0.024, 0.763]} rotation={[0.767, -1.565, -0.805]} scale={[1.909, 0.659, 0.87]} />
        <mesh geometry={nodes.Object_77.geometry} material={materials['Material6-material']} position={[-2.384, 0.018, 0.953]} rotation={[0.767, -1.565, -0.805]} scale={[1.653, 0.352, 1.041]} />
        <mesh geometry={nodes.Object_80.geometry} material={materials['Material32-material']} position={[2.397, 0.036, 0.672]} rotation={[0.767, -1.565, -0.805]} scale={[1.99, 0.151, 0.1]} />
        <mesh geometry={nodes.Object_83.geometry} material={materials['Material6-material']} position={[-0.223, 0.026, 0.916]} rotation={[0.767, -1.565, -0.805]} scale={[2.091, 1.226, 5.357]} />
        <mesh geometry={nodes.Object_86.geometry} material={materials['Material11-material']} position={[2.399, 0.836, 0.594]} rotation={[0.767, -1.565, -0.805]} scale={[0.391, 0.3, 0.092]} />
        <group position={[2.397, 0.036, 0.46]} rotation={[0.767, -1.565, -0.805]} scale={[2.072, 0.267, 0.33]}>
          <mesh geometry={nodes.Object_89.geometry} material={materials['Material33-material']} />
          <mesh geometry={nodes.Object_91.geometry} material={materials['Material34-material']} />
        </group>
        <group position={[1.587, 0.459, 0.403]} rotation={[0.766, -1.565, -0.805]} scale={[0.537, 0.386, 0.47]}>
          <mesh geometry={nodes.Object_94.geometry} material={materials['Material36-material']} />
          <mesh geometry={nodes.Object_96.geometry} material={materials['Material37-material']} />
        </group>
        <mesh geometry={nodes.Object_99.geometry} material={materials['Material38-material']} position={[0.12, 0.028, 0.316]} rotation={[0.767, -1.565, -0.805]} scale={[1.898, 0.124, 2.367]} />
        <mesh geometry={nodes.Object_102.geometry} material={materials['Material3-material']} position={[0.729, 0.03, 1.242]} rotation={[0.766, -1.565, -0.805]} scale={[1.723, 0.393, 0.597]} />
        <group position={[1.59, -0.392, 0.402]} rotation={[0.766, -1.565, -0.805]} scale={[0.537, 0.386, 0.47]}>
          <mesh geometry={nodes.Object_105.geometry} material={materials['Material40-material']} />
          <mesh geometry={nodes.Object_107.geometry} material={materials['Material41-material']} />
        </group>
        <mesh geometry={nodes.Object_110.geometry} material={materials['Material3-material']} position={[-1.526, 0.021, 1.295]} rotation={[0.766, -1.565, -0.805]} scale={[1.382, 0.296, 0.617]} />
        <mesh geometry={nodes.Object_113.geometry} material={materials['Material42-material']} position={[-0.743, 0.024, 0.374]} rotation={[0.766, -1.565, -0.805]} scale={[1.664, 0.498, 2.425]} />
        <group position={[0.277, 0.903, 0.893]} rotation={[0.767, -1.565, -0.805]} scale={[0.322, 1.03, 1.065]}>
          <mesh geometry={nodes.Object_116.geometry} material={materials['Material3-material']} />
          <mesh geometry={nodes.Object_118.geometry} material={materials['Material6-material']} />
          <mesh geometry={nodes.Object_120.geometry} material={materials['Material43-material']} />
          <mesh geometry={nodes.Object_122.geometry} material={materials['Material44-material']} />
          <mesh geometry={nodes.Object_124.geometry} material={materials['Material45-material']} />
          <mesh geometry={nodes.Object_126.geometry} material={materials['Material46-material']} />
        </group>
        <group position={[1.38, 0.065, 0.609]} rotation={[0.767, -1.565, -0.805]} scale={[1.37, 0.748, 1.834]}>
          <mesh geometry={nodes.Object_129.geometry} material={materials['Material47-material']} />
          <mesh geometry={nodes.Object_131.geometry} material={materials['Material48-material']} />
          <mesh geometry={nodes.Object_133.geometry} material={materials['Material49-material']} />
        </group>
        <group position={[0.481, 0.47, 0.984]} rotation={[0.767, -1.565, -0.805]} scale={[0.411, 0.364, 0.301]}>
          <mesh geometry={nodes.Object_136.geometry} material={materials['Material50-material']} />
          <mesh geometry={nodes.Object_138.geometry} material={materials['Material51-material']} />
          <mesh geometry={nodes.Object_140.geometry} material={materials['Material52-material']} />
        </group>
        <mesh geometry={nodes.Object_143.geometry} material={materials['Material53-material']} position={[-1.253, 0.022, 0.401]} rotation={[0.767, -1.565, -0.805]} scale={[1.193, 0.314, 0.139]} />
        <mesh geometry={nodes.Object_146.geometry} material={materials['Material54-material']} position={[-0.127, 0.027, 0.341]} rotation={[0.767, -1.565, -0.805]} scale={[1.86, 0.077, 1.861]} />
        <mesh geometry={nodes.Object_149.geometry} material={materials['Material55-material']} position={[0.058, 0.028, 0.714]} rotation={[0.767, -1.565, -0.805]} scale={[1.788, 0.673, 0.821]} />
        <mesh geometry={nodes.Object_152.geometry} material={materials['Material11-material']} position={[-2.847, 0.016, 0.791]} rotation={[0.767, -1.565, -0.805]} scale={[1.874, 0.08, 0.031]} />
        <mesh geometry={nodes.Object_155.geometry} material={materials['Material11-material']} position={[2.367, 0.036, 0.672]} rotation={[0.767, -1.565, -0.805]} scale={[1.731, 0.151, 0.025]} />
        <group position={[-2.283, 0.018, 0.905]} rotation={[0.767, -1.565, -0.805]} scale={[1.727, 0.446, 1.233]}>
          <mesh geometry={nodes.Object_158.geometry} material={materials['Material56-material']} />
          <mesh geometry={nodes.Object_160.geometry} material={materials['Material57-material']} />
          <mesh geometry={nodes.Object_162.geometry} material={materials['Material58-material']} />
        </group>
        <mesh geometry={nodes.Object_165.geometry} material={materials['Material17-material']} position={[1.638, 0.752, 0.37]} rotation={[0.766, -1.565, -0.805]} scale={[0.226, 0.337, 0.366]} />
        <group position={[-0.792, 0.024, 0.908]} rotation={[0.767, -1.565, -0.805]} scale={[1.823, 1.195, 4.065]}>
          <mesh geometry={nodes.Object_168.geometry} material={materials['Material12-material']} />
          <mesh geometry={nodes.Object_170.geometry} material={materials['Material14-material']} />
          <mesh geometry={nodes.Object_172.geometry} material={materials['Material15-material']} />
          <mesh geometry={nodes.Object_174.geometry} material={materials['Material16-material']} />
          <mesh geometry={nodes.Object_176.geometry} material={materials['Material59-material']} />
          <mesh geometry={nodes.Object_178.geometry} material={materials['Material60-material']} />
          <mesh geometry={nodes.Object_180.geometry} material={materials['Material61-material']} />
        </group>
        <mesh geometry={nodes.Object_183.geometry} material={materials['Material62-material']} position={[1.645, 0.031, 0.657]} rotation={[0.766, -1.565, -0.805]} scale={[1.638, 0.524, 1.281]} />
        <mesh geometry={nodes.Object_186.geometry} material={materials['Material62-material']} position={[0.267, 0.025, 0.525]} rotation={[0.766, -1.565, -0.805]} scale={[1.208, 0.532, 3.615]} />
        <mesh geometry={nodes.Object_189.geometry} material={materials['Material63-material']} position={[-0.773, 0.022, 0.551]} rotation={[0.767, -1.565, -0.805]} scale={[2, 0.497, 4.084]} />
        <mesh geometry={nodes.Object_192.geometry} material={materials['Material64-material']} position={[-0.175, 0.024, 0.752]} rotation={[0.767, -1.565, -0.805]} scale={[2.083, 0.753, 2.039]} />
        <mesh geometry={nodes.Object_195.geometry} material={materials['Material63-material']} position={[-0.202, 0.024, 0.886]} rotation={[0.767, -1.565, -0.805]} scale={[2.05, 1.027, 5.395]} />
        <mesh geometry={nodes.Object_198.geometry} material={materials['Material65-material']} position={[-0.199, 0.024, 0.928]} rotation={[0.766, -1.565, -0.805]} scale={[2.081, 1.056, 5.4]} />
        <mesh geometry={nodes.Object_201.geometry} material={materials['Material63-material']} position={[1.61, 0.031, 0.676]} rotation={[0.767, -1.565, -0.805]} scale={[2.062, 0.765, 1.757]} />
        <mesh geometry={nodes.Object_204.geometry} material={materials['Material62-material']} position={[-0.252, 0.024, 0.449]} rotation={[0.766, -1.565, -0.805]} scale={[1.69, 0.415, 5.039]} />
        <mesh geometry={nodes.Object_207.geometry} material={materials['Material66-material']} position={[2.364, 0.039, 0.469]} rotation={[-0.002, 0.563, -1.566]} scale={[0.348, 0.137, 0.146]} />
        <mesh geometry={nodes.Object_210.geometry} material={materials['Material66-material']} position={[-2.817, 0.016, 0.635]} rotation={[0.002, -0.467, 1.575]} scale={[0.428, 0.12, 0.177]} />
        <mesh geometry={nodes.Object_213.geometry} material={materials['Material68-material']} position={[-2.842, 0.016, 0.632]} rotation={[0.767, -1.565, -0.805]} scale={[2.064, 0.247, 0.168]} />
        <mesh geometry={nodes.Object_216.geometry} material={materials['Material70-material']} position={[-2.788, 0.676, 0.783]} rotation={[0, 0.091, 1.575]} scale={[0.145, 0.124, 0.085]} />
        <mesh geometry={nodes.Object_219.geometry} material={materials['Material70-material']} position={[-2.783, -0.644, 0.783]} rotation={[0, 0.091, 1.575]} scale={[0.145, 0.124, 0.085]} />
        <group position={[-1.464, -0.776, 0.372]} rotation={[0, 0.004, -3.138]} scale={[0.713, 0.266, 0.713]}>
          <mesh geometry={nodes.Object_222.geometry} material={materials['Material72-material']} />
          <mesh geometry={nodes.Object_224.geometry} material={materials['Material73-material']} />
        </group>
        <group position={[1.658, -0.767, 0.359]} rotation={[0, 0.004, -3.138]} scale={[0.713, 0.266, 0.713]}>
          <mesh geometry={nodes.Object_227.geometry} material={materials['Material72-material']} />
          <mesh geometry={nodes.Object_229.geometry} material={materials['Material73-material']} />
        </group>
        <group position={[1.652, 0.831, 0.359]} rotation={[0, 0.004, 0.004]} scale={[0.713, 0.266, 0.713]}>
          <mesh geometry={nodes.Object_232.geometry} material={materials['Material72-material']} />
          <mesh geometry={nodes.Object_234.geometry} material={materials['Material73-material']} />
        </group>
        <group position={[-1.47, 0.819, 0.372]} rotation={[0, 0.004, 0.004]} scale={[0.713, 0.266, 0.713]}>
          <mesh geometry={nodes.Object_237.geometry} material={materials['Material72-material']} />
          <mesh geometry={nodes.Object_239.geometry} material={materials['Material73-material']} />
        </group>
        <mesh geometry={nodes.Object_242.geometry} material={materials['Material26-material']} position={[-2.384, 0.018, 0.953]} rotation={[0.767, -1.565, -0.805]} scale={[1.653, 0.352, 1.041]} />
        <mesh geometry={nodes.Object_245.geometry} material={materials['Material27-material']} position={[-2.384, 0.018, 0.953]} rotation={[0.767, -1.565, -0.805]} scale={[1.653, 0.352, 1.041]} />
        <mesh geometry={nodes.Object_248.geometry} material={materials['Material28-material']} position={[-2.384, 0.018, 0.953]} rotation={[0.767, -1.565, -0.805]} scale={[1.653, 0.352, 1.041]} />
        <mesh geometry={nodes.Object_251.geometry} material={materials['Material29-material']} position={[-2.384, 0.018, 0.953]} rotation={[0.767, -1.565, -0.805]} scale={[1.653, 0.352, 1.041]} />
        <mesh geometry={nodes.Object_254.geometry} material={materials['Material30-material']} position={[-2.384, 0.018, 0.953]} rotation={[0.767, -1.565, -0.805]} scale={[1.653, 0.352, 1.041]} />
      </group>
    </group>
  )
}

useGLTF.preload('/Mustang.gltf')
