/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Rafato.gltf 
Author: rickymovement (https://sketchfab.com/rickymovement)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/1967-muscle-car-ace-rafato-8c245927886b4770aa05bb1a43e4593d
Title: 1967 Muscle Car "Ace Rafato"
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Cars3DModels/Rafato.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <lineSegments geometry={nodes.Object_2.geometry} material={materials.Seats} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Seats} />
        <lineSegments geometry={nodes.Object_4.geometry} material={materials.Chrome_Parts} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Chrome_Parts} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Interior_Base} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.Lights_Textured} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.License_Plate} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.Chassis} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.Lights_Glass} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.Springs} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.Undercarriage} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.Engine_Stuff} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.Glass_Objects} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.Car_Body_Main} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.Chassis_Components} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.Interior_Overall_Parts} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.Interior_Overall_Parts} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.Tyre_FL} />
      </group>
    </group>
  )
}

useGLTF.preload('/Cars3DModels/Rafato.gltf')
